### ISSUE TITLE
`reflex package` fails for custom rules

### ISSUE THREAD

**Issue by mcbanderson** [reflexivesecurity/reflex-cli#223]
reflex-cli version: 1.2.2
Expected result: `reflex package` generated an appropriate lambda package for the rule.
Actual result: Uncaught exception
Steps to reproduce: Add a custom rule to your `reflex.yaml` configuration file and then run `reflex package`
```
rules:
  - detect-large-ec2-instances:
      version: v0.0.2
      configuration:
        github_org: rjulian
```

Based on the stack trace `reflex package` is clearly trying to download the code for this custom rule from the `reflexivesecurity` GitHub org instead of the `rjulian` org as specified. Hopefully this will be an easy fix to point to the correct org.

```
Getting zip from https://api.github.com/repos/reflexivesecurity/reflex-aws-detect-large-ec2-instances/zipball/v0.0.2
Traceback (most recent call last):

...

raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
