### ISSUE TITLE
Malformed `reflex.yaml` config files can cause uncaught exceptions

### ISSUE THREAD

**Issue by mcbanderson** [reflexivesecurity/reflex-cli#95]
We should detect these conditions and provide more user friendly output. Ideally we'll help them identify the malformed part of the config file.

How to replicate:
`reflex.yaml`
```
rules:
  aws:
  - reflex-aws-account-password-policy-deleted:
      configuration:
        mode: remediate  # Note the invalid configuration format here
      version: v0.1.0
```

`reflex build`
